"""
Django settings for KYC project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nucgbovwjwpirm2znqb_ho^ms_8724x9c9z3fse12c(993ay-!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apis',
    'rest_framework',
    'corsheaders',
    'health_check',
    'health_check.db'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "apis.middlewares.log_request",
    #"apis.middlewares.JWT_Authentication",
]

ROOT_URLCONF = 'KYC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KYC.wsgi.application'

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "apis.utils.exceptionhandler.custom_exception_handler",
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    # local
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'cob_new',
    #     'USER': 'root',
    #     'PASSWORD': 'sk@123',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3306',
    # }

    # # prod
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'spclientonboard',
    #     'USER': 'apikyc',
    #     'PASSWORD': 'Hjd%4sdgfdb',
    #     'HOST': '172.16.164.2',
    #     'PORT': '3306',
    # }

    # staging
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kyc_updated',
        'USER': 'root',
        'PASSWORD': 'byself',
        'HOST': 'localhost',
        'PORT': '3306',
    }



    #'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'cobnew',
    #    'USER': 'new_cob',
    #    'PASSWORD': 'MuxqoFZs9TOteqBT',
    #    'HOST': 'archive-db-master.sabpaisa.local',
    #    'PORT': '3306',
    ##}

}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FILE_STORAGE = 'apis.utils.custom_storage.MediaStorage'

# AWS_ACCESS_KEY_ID = "AKIAREIC4XTLOELN6H64"
# AWS_SECRET_ACCESS_KEY = "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"
# AWS_STORAGE_BUCKET_NAME = "cobdocs-stage"


AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", default=None)
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", default=None)
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", default=None)

AWS_QUERYSTRING_AUTH = False
